### ISSUE TITLE
Purpose of package - packaging for distro [13754]

### ISSUE THREAD

**Issue by hansfn** [eProsima/foonathan_memory_vendor#14]
Hi!

I'm maintaining a Gentoo package for Fast-RTPS. In addition I have created packages for dependencies Fast-CDR and foonathan_memory. Everything worked smoothly until this package showed up ;-) (I haven't submitted the packages to Gentoo yet, and they are only available on our company Git server, not here on GitHub.)

Is there really a need for this package? The [installation directory issue](https://github.com/foonathan/memory/issues/48) is resolved and a [new release of foonathan_memory](https://github.com/foonathan/memory/releases/tag/v0.6-2) has been created. Can't Fast-RTPS just depend on that version of foonathan/memory?

There might of course be very good reasons for creating this vendor package, but for distro packaging I think it's a drawback.

PS! Splitting Fast-RTPS-Gen as an independent project was a good decision.

**Comment by MiguelCompany** [comment]
@hansfn If foonathan_memory is installed in the system, and you build Fast-RTPS using cmake, there is no need for this package. This package is only useful when building with colcon, especially on ROS2. In that case, it will download and build foonathan_memory ONLY if not found in the system.

**Comment by hansfn** [comment]
Thanks for the clarification. Then I think you should update https://github.com/eProsima/Fast-RTPS/blob/master/README.md 

Under "[Manual installation](https://github.com/eProsima/Fast-RTPS/blob/master/README.md#manual-installation)" foonathan_memory_vendor is used even if you are building with Cmake. The link goes to foonathan_memory, but it really looks as we have to install foonathan_memory_vendor.

**Comment by JLBuenoLopez** [comment]
The manual installation is no longer kept in Fast DDS README but in Fast DDS documentation. I think this issue can be closed.
