### ISSUE TITLE
Release into the ROS buildfarm

### ISSUE THREAD

**Issue by esteve** [eProsima/foonathan_memory_vendor#16]
It'd be really useful if this package were released into the ROS buildfarm for other packages to depend on it. I'm happy to help with whatever's needed.

**Comment by MiguelCompany** [comment]
Bringin in @nuclearsandwich who is also a mantainer of this repo

**Comment by nuclearsandwich** [comment]
@esteve what ROS distribution are you expecting a release in? This package is coming as part of Eloquent since it's required for Fast-RTPS.

**Comment by esteve** [comment]
@nuclearsandwich could you release it for Dashing as well? At Apex we plan to release some stuff that depends on `foonathan_memory` and having this packaged would help a lot.

**Comment by nuclearsandwich** [comment]
https://github.com/ros/rosdistro/pull/22805

**Comment by nuclearsandwich** [comment]
The above PR has been merged and foonathan_memory_vendor will be in the next Dashing sync.

**Comment by esteve** [comment]
@nuclearsandwich sorry for the late response, thank you so much!
