### ISSUE TITLE
Progress toward Quality Level 1 [13755]

### ISSUE THREAD

**Issue by Blast545** [eProsima/foonathan_memory_vendor#21]
This issue tracks the progression of the package `foonathan_memory_vendor` that have been deemed necessary for Quality Level 1 and version 1.0. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/rep-2004/rep-2004.rst). 

Versioning
* [x] Version Policy
    - Follows ROS Core Quality Declaration
* [x] Change Control Process
    - Follows ROS Core
* [ ] Version >= 1.0.0

Documentation
* [x] Declared set of licenses
* [x] Copyright statement in each source file
  - No source files in this package

Dependencies:
* [ ] Non-ROS dependencies are equivalent level 1
  - Needs to justify that foonathan_memory is quality level 1

Platform Support
* [x] Supports all tier 1 platforms

Documentation
* [ ] Per-feature documentation.
* [ ] Per-item documentation in public API. 
* [ ] Quality Declaration document

Testing:
* [ ] Must have system tests which cover all items in the "feature" documentation
  - Tests for the imported library are valid?
* [ ] Must have system, integration, and/or unit tests which cover all of the public API
* [ ] Code Coverage:
  - * [ ] Must have code coverage tracking for the package.
  - * [x] Must have and enforce a code coverage policy for new changes [Policy](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#coverage)
* [ ] Performance:
  - * [ ] Must have performance tests 
  - * [x] Must have a performance regression policy (i.e. blocking either changes or releases on unexpected performance regressions). -> [Policy](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#performance)
* [ ] Linters and Static Analysis:
  - * [x] Must have a code style and enforce it
  - * [x] Must use static analysis tools where applicable: ament_lint_common applied to the files belonging to this repo.

**Comment by JLBuenoLopez** [comment]
@Blast545,

I do not know if we need to keep this ticket opened. Fast DDS repository includes a [Quality Declaration](https://github.com/eProsima/Fast-DDS/blob/master/Quality_Declaration_foonathan_memory.md) of `foonathan memory` which also refers to this package. This Quality Declaration conforms to the [ROS 2 REP2004 specifications](https://ros.org/reps/rep-2004.html).

**Comment by Blast545** [comment]
I wasn't actively tracking this, I just saw this document in this repo: [foonathan_memory_vendor QD](https://github.com/eProsima/foonathan_memory_vendor/blob/master/QUALITY_DECLARATION.md)

So I agree it's ok to close this issue.
