### ISSUE TITLE
Create release for Dashing and Eloquent with Pinned Version

### ISSUE THREAD

**Issue by mjcarroll** [eProsima/foonathan_memory_vendor#25]
Now that https://github.com/eProsima/foonathan_memory_vendor/pull/24 introduces a pinned version for the upstream `foonathan/memory`, we need a tagged version that incorporates this change for Dashing and Eloquent.

**Comment by MiguelCompany** [comment]
@mjcarroll I think that eloquent and dashing could use the 1.0.0 release of this package, as it is still pinned to the same upstream version of `foonathan/memory`

**Comment by MiguelCompany** [comment]
@mjcarroll Friendly ping

**Comment by MiguelCompany** [comment]
@mjcarroll I've seen that ros2/ros2#892 has been closed. Perhaps we can also close this one?
