### ISSUE TITLE
nodesize_dbg: not found

### ISSUE THREAD

**Issue by mauropasse** [eProsima/foonathan_memory_vendor#33]
When cross-compiling for RPi2, I got this error:
```
HEAD is now at c619113 Whitespace clean up (#70)
Submodule 'cmake/comp' (https://github.com/foonathan/compatibility.git) registered for path 'cmake/comp'
Cloning into '/root/ws/build/foonathan_memory_vendor/foo_mem-ext-prefix/src/foo_mem-ext/cmake/comp'...
/bin/sh: 1: ../tool/nodesize_dbg: not found
make[5]: *** [src/container_node_sizes_impl.hpp] Error 127
make[4]: *** [src/CMakeFiles/foonathan_memory.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [foo_mem-ext-prefix/src/foo_mem-ext-stamp/foo_mem-ext-build] Error 2
make[1]: *** [CMakeFiles/foo_mem-ext.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< foonathan_memory_vendor	[ Exited with code 2 ]
```
A workaround is made in this PR: https://github.com/eProsima/foonathan_memory_vendor/pull/32

But the tool is actually present in
`./build/foonathan_memory_vendor/foo_mem-ext-prefix/src/foo_mem-ext-build/tool/nodesize_dbg`

So there should be a way to not use the option I added in the PR

**Comment by MiguelCompany** [comment]
If you are cross-compiling, it may just be that the tool is found but cannot be executed. Adding an emulator to your toolchain file should do the work.

See foonathan/memory#60 for details.

**Comment by MiguelCompany** [comment]
@mauropasse Did you get to solve this? Can this issue be closed?

**Comment by mauropasse** [comment]
Hi @MiguelCompany , the PR https://github.com/eProsima/foonathan_memory_vendor/pull/32 fixes the issue. Thanks!
