### ISSUE TITLE
need to update foonathan source used to include QNX patch in it

### ISSUE THREAD

**Issue by asobhy-qnx** [eProsima/foonathan_memory_vendor#37]
foonathan memory was patched for QNX on commit 1cfcebe5c3af3e68d5a0a2f9f4c231bf057d74d0

**Comment by asobhy-qnx** [comment]
@MiguelCompany Can you please let me know how if you would like me to create PR for this issue?

**Comment by MiguelCompany** [comment]
@asobhy-qnx Version was pinned on #24 due to regressions on ROS 2 CI. But this is a vendor package, so if you build and install foonathan memory before building this package, the one installed on the system will be used.

**Comment by pablorcum** [comment]
Some more changes were added recently that ease crosscompiling to QNX Neutrino. The GIT_TAG to set at the main CMakeLists.txt shall be now [bc300f41d5cb78b458d5c7d62058fbe1f9bce54b](https://github.com/foonathan/memory/commit/bc300f41d5cb78b458d5c7d62058fbe1f9bce54b).
