### ISSUE TITLE
Error building on macOS Big Sur (Foxy)

### ISSUE THREAD

**Issue by AndrewJSchoen** [eProsima/foonathan_memory_vendor#43]
Hi,

I am attempting to build ROS2 Foxy from source on macOS 11 Big Sur. So far, most packages were compiling fine.

However, when colcon gets to this package, I get the following error:

```
[Processing: foonathan_memory_vendor]                                       
--- stderr: foonathan_memory_vendor                                         
* Closing connection 0
CMake Error at cmake/comp/comp_base.cmake:288 (message):
  error downloading feature file cpp11_lib/max_align_t.cmake: "Couldn't
  connect to server".  Check spelling of feature.

    Trying 199.232.28.133...

  TCP_NODELAY set

  Connection failed

  connect to 199.232.28.133 port 443 failed: Operation timed out

  Failed to connect to raw.githubusercontent.com port 443: Operation timed
  out

  Closing connection 0

Call Stack (most recent call first):
  cmake/comp/comp_base.cmake:347 (_comp_fetch_feature)
  cmake/comp/comp_base.cmake:369 (_comp_handle_feature)
  cmake/compatibility.cmake:13 (comp_target_features)
  CMakeLists.txt:50 (include)


make[2]: *** [foo_mem-ext-prefix/src/foo_mem-ext-stamp/foo_mem-ext-configure] Error 1
make[1]: *** [CMakeFiles/foo_mem-ext.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< foonathan_memory_vendor [1min 31s, exited with code 2]
```

I am on the master branch. Let me know if any additional information would be helpful.

Thanks!

**Comment by MiguelCompany** [comment]
>   Failed to connect to raw.githubusercontent.com port 443: Operation timed out

When this package is built, it will clone and build foonathan/memory@c619113
The repo being cloned has some submodules, and your build is failing when cloning those. The connection with https://raw.githubusercontent.com timed out.

**Comment by AndrewJSchoen** [comment]
Hi @MiguelCompany, thanks for the response! I had noted that in the error log, and tried it a couple times to see if it was a one-off, but it seemed to persist. I tried again this morning, and after failing once again, it succeeded. Not sure exactly what was causing that, but it seems to have resolved itself for the time being, and it is probably something to do with my machine.
