### ISSUE TITLE
foonathan_memory can't install [13759]

### ISSUE THREAD

**Issue by wangkaigit** [eProsima/foonathan_memory_vendor#48]
Why did foonathan_memory fail to install recently, Something was suggested to have failed to download during installation， Is there a solution？ thanks

**Comment by barbara-schraml** [comment]
I had to replace the git version in the cmake file:
(around line 79:) 

GIT_TAG something 

to

GIT_TAG v0.7

**Comment by nuclearsandwich** [comment]
Can you please provide more information about the installation failure? This vendor package is being used as-is on a nightly basis in ROS 2.
