### ISSUE TITLE
foo_mem-ext error

### ISSUE THREAD

**Issue by Baren123** [eProsima/foonathan_memory_vendor#51]
when I perform make，the following error will be reported

[ 12%] Creating directories for 'foo_mem-ext'
[ 25%] Performing download step (git clone) for 'foo_mem-ext'
Cloning into 'foo_mem-ext'...
HEAD is now at c619113 Whitespace clean up (#70)
Submodule 'cmake/comp' (https://github.com/foonathan/compatibility.git) registered for path 'cmake/comp'
Cloning into '/home/wd/work/dds/foonathan_memory_vendor/build/foo_mem-ext-prefix/src/foo_mem-ext/cmake/comp'...
Submodule path 'cmake/comp': checked out 'cd142129e30f5b3e6c6d96310daf94242c0b03bf'
[ 37%] No update step for 'foo_mem-ext'
[ 50%] No patch step for 'foo_mem-ext'
[ 62%] Performing configure step for 'foo_mem-ext'
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking flags for C++11
-- Checking flags for C++11 - Found: -std=c++11
-- Checking flags for C++14
-- Checking flags for C++14 - Found: -std=c++14
-- Checking flags for C++17
-- Checking flags for C++17 - Found: -std=c++17
-- Checking 13 features
**CMake Error at cmake/comp/comp_base.cmake:288 (message):
  error downloading feature file cpp11_lang/alignas.cmake: "SSL connect
  error".  Check spelling of feature.

    Trying 185.199.111.133:443...

  Connected to raw.githubusercontent.com (185.199.111.133) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

   CAfile: /etc/ssl/certs/ca-certificates.crt
   CApath: /etc/ssl/certs

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  OpenSSL SSL_connect: Connection reset by peer in connection to
  raw.githubusercontent.com:443

  Closing connection 0

Call Stack (most recent call first):
  cmake/comp/comp_base.cmake:347 (_comp_fetch_feature)
  cmake/comp/comp_base.cmake:369 (_comp_handle_feature)
  cmake/compatibility.cmake:13 (comp_target_features)
  CMakeLists.txt:50 (include)**

-- Configuring incomplete, errors occurred!
See also "/home/wd/work/dds/foonathan_memory_vendor/build/foo_mem-ext-prefix/src/foo_mem-ext-build/CMakeFiles/CMakeOutput.log".
CMakeFiles/foo_mem-ext.dir/build.make:91: recipe for target 'foo_mem-ext-prefix/src/foo_mem-ext-stamp/foo_mem-ext-configure' failed
make[2]: *** [foo_mem-ext-prefix/src/foo_mem-ext-stamp/foo_mem-ext-configure] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/foo_mem-ext.dir/all' failed
make[1]: *** [CMakeFiles/foo_mem-ext.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

How can I solve this problem?

**Comment by MiguelCompany** [comment]
This should be fixed by #49

**Comment by MiguelCompany** [comment]
Closing this via #49
