### ISSUE TITLE
New release for Foxy?

### ISSUE THREAD

**Issue by jacobperron** [eProsima/foonathan_memory_vendor#54]
I noticed that Foxy from-source is [pointing to `master`](https://github.com/ros2/ros2/blob/75b13d3db080df51b75e5720e6f8ae043c0aa092/ros2.repos#L45), which I think is at v1.2.0. But, the currently [released version in Foxy is 1.0.0](https://github.com/ros/rosdistro/blob/master/foxy/distribution.yaml#L1208). Should we make a 1.2.0 release for Foxy? @MiguelCompany @richiware 

Alternatively, we can pin the version in the ros2.repos file.

**Comment by MiguelCompany** [comment]
@jacobperron I went ahead and run `bloom-release` for both foxy and galactic.

See ros/rosdistro#32093 and ros/rosdistro#32094
