### ISSUE TITLE
  cannot generate container_node_sizes_impl.hpp, node size information will   be unavailable [13937]

### ISSUE THREAD

**Issue by Nir-Az** [eProsima/foonathan_memory_vendor#56]
Hi 
When configuring foonathan memory I get this CMake warning.
```
  cannot generate container_node_sizes_impl.hpp, node size information will
  be unavailable
```

Is it because I turn off the BUILD_TOOLS flag?
will it cause memory issues / performance issues on FastDDS runtime?

**Comment by MiguelCompany** [comment]
> Is it because I turn off the BUILD_TOOLS flag?

Yes. This will disable the generation of the `container_node_sizes_impl.hpp` contents.

> will it cause memory issues / performance issues on FastDDS runtime?

It will increase memory usage a bit, since Fast DDS will guess the node size [here](https://github.com/eProsima/Fast-DDS/blob/master/src/cpp/utils/collections/impl/node-sizes/custom/tree_node_size_impl.hpp), which takes the size of a custom node that includes the fields of all the common implementations.

**Comment by Nir-Az** [comment]
Thanks @MiguelCompany ,
So FastDDS recomendation is to turn on the tools build?
Not sure why they coupled an executable build with a library feature..

**Comment by MiguelCompany** [comment]
@Nir-Az 

If you don't want to (or cannot due to system requirements) build and run the tool, you could use the generous external contribution that was recently merged on foonathan/memory#129

**Comment by Nir-Az** [comment]
@MiguelCompany I can turn the flag on and test if it builds OK, but what did you mean with running it?

I am consuming FastDDS library and use it's API.
When/Why should I run this foonathan tool?

Didn't find something about it on FastDDS documentation.

**Comment by MiguelCompany** [comment]
@Nir-Az 

The tool is run as a build step. See [here](https://github.com/foonathan/memory/blob/v0.7-1/src/CMakeLists.txt#L81). When cross-compiling, it can be run on an emulator.

foonathan/memory#129 changes this to use CMake machinery to generate `container_node_sizes_impl.hpp`

**Comment by Nir-Az** [comment]
Great, thanks for the help.
